#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

STOP=10
stop() {
	PID=`/usr/bin/pgrep -f "python -u bridge.py"`
	if [ "x$PID" != "x" ]; then
		/usr/bin/kill-bridge
		echo "kill bridge" > /dev/ttyATH0 2>&1
		/usr/bin/reset-mcu
		echo "reset mcu..." > /dev/ttyATH0 2>&1
	fi
}
